'use client';

import { useEffect, useMemo, useState } from 'react';
import SubmitPicks from '@/components/SubmitPicks';
import PickCard from '@/components/PickCard';
import WeeklyPickGrid from '@/components/WeeklyPickGrid';
import type { ContestGame, Pick, Player, Week } from '@/types';

const demoWeek: Week = { id: 'week-3', season: 2026, weekNumber: 3, name: 'Week 3', status: 'open', pickLockAt: '2026-09-19T16:00:00.000Z' };
const demoWeeks = [{ id: 'week-1', name: 'Week 1' }, { id: 'week-2', name: 'Week 2' }, { id: 'week-3', name: 'Week 3' }];
const players: Player[] = ['Nate-290', 'longrangeangeing44', 'Tannerbeck14', 'Kaderade5', 'kellyturley', 'Schwartz_B', 'WTURLEY', 'kbake13', 'DUCE2244', 'coopballer2', 'BLEEBECK', 'Bridger-Jones', 'jedforest', 'blairfrei3', 'Uruguay-No-Mas', 'Tanner-Hansen', 'jthatch21', 'Landonbeck'].map((displayName) => ({ id: displayName.toLowerCase(), displayName }));
const demoGames: ContestGame[] = [
  { id: 'g1', weekId: demoWeek.id, spreadTeam: 'BYU', spreadValue: -3.5, displayOrder: 1, game: { id: 'g1', weekId: demoWeek.id, awayTeam: 'BYU', awayAbbr: 'BYU', awayLogo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/252.png', homeTeam: 'Utah', homeAbbr: 'UTAH', homeLogo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/254.png', kickoffAt: '2026-09-20T02:15:00Z', status: 'scheduled' } },
  { id: 'g2', weekId: demoWeek.id, spreadTeam: 'Texas', spreadValue: -4, displayOrder: 2, game: { id: 'g2', weekId: demoWeek.id, awayTeam: 'Texas', awayAbbr: 'TEX', awayLogo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/251.png', homeTeam: 'Oklahoma', homeAbbr: 'OU', homeLogo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/201.png', kickoffAt: '2026-09-19T19:00:00Z', status: 'scheduled' } },
  { id: 'g3', weekId: demoWeek.id, spreadTeam: 'Oregon', spreadValue: 2, displayOrder: 3, game: { id: 'g3', weekId: demoWeek.id, awayTeam: 'USC', awayAbbr: 'USC', awayLogo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/30.png', homeTeam: 'Oregon', homeAbbr: 'ORE', homeLogo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2483.png', kickoffAt: '2026-09-18T01:00:00Z', status: 'scheduled' } },
  { id: 'g4', weekId: demoWeek.id, spreadTeam: 'Georgia', spreadValue: -7, displayOrder: 4, game: { id: 'g4', weekId: demoWeek.id, awayTeam: 'Georgia', awayAbbr: 'UGA', awayLogo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/61.png', homeTeam: 'Kentucky', homeAbbr: 'UK', homeLogo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/96.png', kickoffAt: '2026-09-19T17:00:00Z', status: 'scheduled' } },
];
demoGames.push(...Array.from({ length: 12 }, (_, index) => { const number = index + 5; const kickoff = new Date(Date.UTC(2026, 8, 18 + (index % 3), 18 + index, 0)).toISOString(); return { id: `g${number}`, weekId: demoWeek.id, spreadTeam: `Team ${number}A`, spreadValue: -1.5, displayOrder: number, game: { id: `g${number}`, weekId: demoWeek.id, awayTeam: `Team ${number}A`, awayAbbr: `T${number}A`, homeTeam: `Team ${number}B`, homeAbbr: `T${number}B`, kickoffAt: kickoff, status: 'scheduled' as const } }; }));
const initialPicks: Pick[] = [{ id: 'p1', userId: 'bridger-jones', contestGameId: 'g1', selectedTeam: 'BYU', selectedSpread: -3.5, confidencePoints: 10, result: 'pending' }, { id: 'p2', userId: 'bridger-jones', contestGameId: 'g2', selectedTeam: 'Oklahoma', selectedSpread: 4, confidencePoints: 9, result: 'pending' }];
const historicalDemo = [{ name: 'Nate-290', wins: 14, losses: 6, points: 75, tieDiff: 2 }, { name: 'longrangeangeing44', wins: 11, losses: 9, points: 66, tieDiff: 8 }, { name: 'Tannerbeck14', wins: 10, losses: 10, points: 64, tieDiff: 7 }, { name: 'Kaderade5', wins: 11, losses: 9, points: 62, tieDiff: 8 }, { name: 'kellyturley', wins: 12, losses: 8, points: 60, tieDiff: 15 }, { name: 'Schwartz_B', wins: 10, losses: 10, points: 59, tieDiff: 4 }, { name: 'WTURLEY', wins: 11, losses: 9, points: 58, tieDiff: 2 }, { name: 'kbake13', wins: 10, losses: 10, points: 55, tieDiff: 19 }, { name: 'DUCE2244', wins: 10, losses: 10, points: 54, tieDiff: 7 }, { name: 'coopballer2', wins: 8, losses: 12, points: 53, tieDiff: 4 }, { name: 'BLEEBECK', wins: 9, losses: 11, points: 51, tieDiff: 7 }, { name: 'Bridger-Jones', wins: 9, losses: 11, points: 48, tieDiff: 1 }, { name: 'jedforest', wins: 9, losses: 11, points: 45, tieDiff: 4 }, { name: 'blairfrei3', wins: 8, losses: 12, points: 45, tieDiff: 7 }, { name: 'Uruguay-No-Mas', wins: 8, losses: 12, points: 41, tieDiff: 6 }, { name: 'Tanner-Hansen', wins: 6, losses: 14, points: 37, tieDiff: 54 }, { name: 'jthatch21', wins: 7, losses: 3, points: 32, tieDiff: 12 }, { name: 'Landonbeck', wins: 5, losses: 15, points: 19, tieDiff: 64 }];
const formatKickoff = (date: string) => new Intl.DateTimeFormat(undefined, { weekday: 'short', hour: 'numeric', minute: '2-digit' }).format(new Date(date));
const displaySpread = (game: ContestGame, team: string) => { const value = game.spreadTeam === team ? game.spreadValue : -game.spreadValue; return value > 0 ? `+${value}` : String(value); };

type Standing = { player: Player; wins: number; losses: number; pushes: number; winPercentage: number; firstPlace?: number; secondPlace?: number; thirdPlace?: number; points?: number; tieDiff?: number; moneyEarned?: number };
function Standings({ season, weekId, weekNumber, weekStatus }: { season?: boolean; weekId: string; weekNumber: number; weekStatus: Week['status'] }) {
  const [liveRows, setLiveRows] = useState<Standing[] | null>(null);
  useEffect(() => { if (process.env.NEXT_PUBLIC_DEMO_MODE === 'true') return; fetch(`/api/standings${season ? '?season=2026' : `?weekId=${weekId}`}`).then((response) => response.ok ? response.json() : null).then((result) => setLiveRows(result?.standings ?? null)).catch(() => setLiveRows(null)); }, [season, weekId]);
  if (!season && weekStatus !== 'completed') return <div className="empty">Weekly standings will appear once {`Week ${weekNumber}`} is completed.</div>;
  const finishes: Record<string, [number, number, number]> = { coopballer2: [1, 0, 0], kellyturley: [0, 1, 0], BLEEBECK: [0, 0, 1], Tannerbeck14: [1, 0, 0], longrangeangeing44: [0, 1, 0], 'Nate-290': [0, 0, 1] };
  const prizeMoney: Record<string, number> = { coopballer2: 115, kellyturley: 70, BLEEBECK: 35, Tannerbeck14: 115, longrangeangeing44: 70, 'Nate-290': 35 };
  const rows: Standing[] = liveRows ?? historicalDemo.map((item) => { const finish = finishes[item.name] ?? [0, 0, 0]; return { player: players.find((player) => player.displayName === item.name)!, wins: item.wins, losses: item.losses, pushes: 0, points: season ? item.points : undefined, tieDiff: season ? item.tieDiff : undefined, moneyEarned: season ? prizeMoney[item.name] ?? 0 : undefined, firstPlace: finish[0], secondPlace: finish[1], thirdPlace: finish[2], winPercentage: item.wins / (item.wins + item.losses) }; });
  return <><div className="intro"><div><div className="eyebrow">{season ? '2026 season' : `Week ${weekNumber}`}</div><h1>{season ? 'Season standings' : 'Weekly results'}</h1><p>{season ? 'The full season race, updated after games are graded.' : 'Results and the 16-game pick spreadsheet for each completed week.'}</p></div><select aria-label="Select week" defaultValue={season ? 'season' : String(weekNumber)}>{season&&<option value="season">Full season</option>}{!season&&[1,2,3].map(number=><option key={number} value={number}>Week {number}</option>)}</select></div><div className="table-wrap"><table><thead><tr><th>Rank</th><th>Player</th>{season&&<th>Points</th>}<th>Record</th><th>1st</th><th>2nd</th><th>3rd</th>{season&&<th>Money earned</th>}</tr></thead><tbody>{rows.map((row, index) => <tr key={row.player.id}><td className="rank">{index + 1}</td><td><strong>{row.player.displayName}</strong></td>{season&&<td className="record">{row.points??0}</td>}<td className="record">{row.wins}-{row.losses}{row.pushes ? `-${row.pushes}` : ''}</td><td>{row.firstPlace??0}</td><td>{row.secondPlace??0}</td><td>{row.thirdPlace??0}</td>{season&&<td className="record">${row.moneyEarned??0}</td>}</tr>)}</tbody></table></div></>;
}

export default function Home() {
  const [tab, setTab] = useState<'picks' | 'weekly' | 'season'>('picks');
  const [week, setWeek] = useState(demoWeek);
  const [games, setGames] = useState(demoGames);
  const [picks, setPicks] = useState(initialPicks);
  const [viewer, setViewer] = useState(players.find((player) => player.displayName === 'Bridger-Jones') ?? players[0]);
  const [now, setNow] = useState(new Date());
  useEffect(() => { const timer = window.setInterval(() => setNow(new Date()), 30000); return () => window.clearInterval(timer); }, []);
  useEffect(() => { fetch('/api/auth/me').then((response) => response.ok ? response.json() : null).then((result) => { if (result?.user) setViewer({ id: result.user.id, displayName: result.user.displayName }); }).catch(() => undefined); }, []);
  useEffect(() => { if (process.env.NEXT_PUBLIC_DEMO_MODE === 'true') return; fetch('/api/contest').then((response) => response.ok ? response.json() : null).then((result) => { if (!result) return; setWeek({ id: result.week.id, season: result.week.season, weekNumber: result.week.week_number, name: result.week.name, status: result.week.status, pickLockAt: result.week.pick_lock_at }); setGames((result.games ?? []).map((row: Record<string, unknown>) => { const game = row.games as Record<string, unknown>; return { id: String(row.id), weekId: String(row.week_id), spreadTeam: String(row.spread_team), spreadValue: Number(row.spread_value), displayOrder: Number(row.display_order), game: { id: String(game.id), weekId: String(game.week_id), awayTeam: String(game.away_team), awayAbbr: String(game.away_team_abbreviation), awayLogo: typeof game.away_team_logo === 'string' ? game.away_team_logo : undefined, homeTeam: String(game.home_team), homeAbbr: String(game.home_team_abbreviation), homeLogo: typeof game.home_team_logo === 'string' ? game.home_team_logo : undefined, kickoffAt: String(game.kickoff_at), status: game.game_status as ContestGame['game']['status'] } }; })); setPicks((result.picks ?? []).map((pick: Record<string, unknown>) => ({ id: String(pick.id), userId: String(pick.user_id), contestGameId: String(pick.contest_game_id), selectedTeam: String(pick.selected_team), selectedSpread: Number(pick.selected_spread), confidencePoints: Number(pick.confidence_points), result: pick.result as Pick['result'] }))); }).catch(() => undefined); }, []);
  const locked = now >= new Date(week.pickLockAt); const ownPicks = picks.filter((pick) => pick.userId === viewer.id); const visiblePicks = locked ? picks : ownPicks; const visibleByGame = useMemo(() => new Map(visiblePicks.map((pick) => [`${pick.userId}:${pick.contestGameId}`, pick])), [visiblePicks]); const remaining = Math.max(0, 10 - ownPicks.length); const countdownMs = Math.max(0, new Date(week.pickLockAt).getTime() - now.getTime()); const countdown = `${Math.floor(countdownMs / 3600000)}h ${Math.floor((countdownMs % 3600000) / 60000)}m`;
  const choose = async (game: ContestGame, team: string, confidencePoints: number): Promise<{ ok: true } | { ok: false; error: string }> => { if (locked || now >= new Date(game.game.kickoffAt)) return { ok: false, error: 'This game is locked.' }; if (!picks.some((pick) => pick.userId === viewer.id && pick.contestGameId === game.id) && ownPicks.length >= 10) return { ok: false, error: 'You already selected 10 games.' }; const selectedSpread = Number(displaySpread(game, team)); if (process.env.NEXT_PUBLIC_DEMO_MODE !== 'true') { try { const response = await fetch('/api/picks', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ contestGameId: game.id, selectedTeam: team, confidencePoints }) }); const result = await response.json().catch(() => null); if (!response.ok) return { ok: false, error: result?.error || 'Pick could not be saved.' }; } catch { return { ok: false, error: 'Check your connection and try again.' }; } } setPicks((current) => [...current.filter((pick) => !(pick.userId === viewer.id && pick.contestGameId === game.id)), { id: crypto.randomUUID(), userId: viewer.id, contestGameId: game.id, selectedTeam: team, selectedSpread, confidencePoints, result: 'pending' }]); return { ok: true }; };
  return <><header className="topbar"><div className="topbar-inner"><div className="wordmark">CFB <span>PICKS</span></div><div className="user-chip">{viewer.displayName} · Private league</div></div></header><main className="shell"><nav className="tabs">{([['picks', 'Make Your Picks'], ['weekly', 'Weekly Results'], ['season', 'Season']] as const).map(([id, label]) => <button key={id} className={`tab ${tab === id ? 'active' : ''}`} onClick={() => setTab(id)}>{label}</button>)}</nav>
    {tab === 'picks' && <><div className="intro"><div><div className="eyebrow">2026 college football</div><h1>{week.name}</h1><p>Pick 10 games and assign confidence values 1 through 10.</p></div><div className="progress"><strong>{ownPicks.length} of 10</strong> picks complete</div></div><div className={`notice ${locked ? 'status-locked' : ''}`}><div><strong>{locked ? 'PICKS LOCKED' : 'Picks lock Saturday at 10:00 AM'}</strong><small>{locked ? 'Selections are final. Everyone’s picks are visible.' : `${countdown} remaining · America/Denver`}</small></div>{!locked && remaining > 0 && <strong>{remaining} pick{remaining === 1 ? '' : 's'} remaining</strong>}</div><SubmitPicks weekId={week.id} complete={ownPicks.length} /><div className="grid">{games.map((game) => { const own = visibleByGame.get(`${viewer.id}:${game.id}`); const usedConfidencePoints = ownPicks.filter((pick) => pick.contestGameId !== game.id).map((pick) => pick.confidencePoints).filter((value): value is number => typeof value === 'number'); return <PickCard key={game.id} game={game} pick={own} usedConfidencePoints={usedConfidencePoints} locked={locked} gameLocked={now >= new Date(game.game.kickoffAt)} formatKickoff={formatKickoff} displaySpread={displaySpread} onSave={choose} />; })}</div>{locked && <><div className="intro" style={{marginTop:38}}><div><div className="eyebrow">League view</div><h2>Everyone’s picks</h2><p>Selections remain private until the universal deadline.</p></div></div><div className="table-wrap"><table><thead><tr><th>Game</th>{players.map((player) => <th key={player.id}>{player.displayName}</th>)}</tr></thead><tbody>{games.map((game) => <tr key={game.id}><td><strong>{game.game.awayAbbr} @ {game.game.homeAbbr}</strong></td>{players.map((player) => <td key={player.id}>{visibleByGame.get(`${player.id}:${game.id}`)?.selectedTeam || '—'}</td>)}</tr>)}</tbody></table></div></>}</>}
    {tab === 'weekly' && <><Standings weekId={week.id} weekNumber={week.weekNumber} weekStatus={week.status} /><WeeklyPickGrid week={week} games={games} players={players} initialPicks={[]} viewerId={viewer.id} /></>}
    {tab === 'season' && <Standings season weekId={week.id} weekNumber={week.weekNumber} weekStatus={week.status} />}
  </main></>;
}
