'use client';
import { useEffect, useState } from 'react';
import type { ContestGame, Pick, Player, Week } from '@/types';
type Cell={userId:string;contestGameId:string;selectedTeam:string;confidencePoints?:number;points?:number;result?:'pending'|'win'|'loss'|'push'};
export default function WeeklyPickGrid({week,games,players,initialPicks,viewerId}:{week:Week;games:ContestGame[];players:Player[];initialPicks:Pick[];viewerId:string}){
 const [board,setBoard]=useState({games,players,picks:initialPicks as Cell[],public:false});
 useEffect(()=>{if(process.env.NEXT_PUBLIC_DEMO_MODE==='true')return;fetch(`/api/weekly-board?weekId=${week.id}`).then(response=>response.ok?response.json():null).then(result=>{if(result)setBoard({games:result.games.map((row:Record<string,unknown>)=>{const game=row.games as Record<string,unknown>;return{id:String(row.id),weekId:String(row.week_id),spreadTeam:String(row.spread_team),spreadValue:Number(row.spread_value),displayOrder:Number(row.display_order),game:{id:String(row.game_id),weekId:String(row.week_id),awayTeam:String(game.away_team),awayAbbr:String(game.away_team_abbreviation),homeTeam:String(game.home_team),homeAbbr:String(game.home_team_abbreviation),kickoffAt:String(game.kickoff_at),status:'scheduled'}};}),players:result.users.map((user:{id:string;display_name:string})=>({id:user.id,displayName:user.display_name})),picks:result.picks,public:result.public});}).catch(()=>undefined);},[week.id]);
 const cells=new Map(board.picks.map(pick=>[`${pick.userId}:${pick.contestGameId}`,pick]));
 const rows=board.players.map(player=>{const picks=board.games.map(game=>cells.get(`${player.id}:${game.id}`));const total=picks.reduce((sum,pick)=>sum+(pick?.points??(pick?.result==='win'?pick.confidencePoints??0:0)),0);return{player,picks,total};}).sort((a,b)=>b.total-a.total||a.player.displayName.localeCompare(b.player.displayName));
 const spread=(game:ContestGame,team:string)=>{const value=game.spreadTeam===team?game.spreadValue:-game.spreadValue;return value>0?`+${value}`:String(value);};
 return <section style={{marginTop:28}}><div className="eyebrow">Weekly pick sheet</div><h2>{board.public?'Results':'Your picks only'}</h2><p style={{color:'var(--muted)'}}>{board.public?'Green bubbles are wins. Red bubbles are losses. Blank cells are missing picks.':'Other contestants remain hidden until the 10:00 AM deadline.'}</p><div className="table-wrap"><table className="pick-sheet rotated"><thead><tr><th>Rank / contestant</th>{board.games.map(game=><th key={game.id}><strong className="game-heading">{game.game.awayAbbr} @ {game.game.homeAbbr}</strong><small style={{display:'block'}}>{spread(game,game.game.awayTeam)} / {spread(game,game.game.homeTeam)}</small></th>)}<th>Total points</th></tr></thead><tbody>{rows.map((row,index)=><tr key={row.player.id}><td><strong className="rank-bubble">{index+1}. {row.player.displayName}</strong></td>{row.picks.map((pick,index2)=>{const visible=board.public||row.player.id===viewerId;return <td key={board.games[index2].id} className={visible&&pick?.result==='win'?'pick-win':visible&&pick?.result==='loss'?'pick-loss':''}>{visible&&pick?<span className="pick-bubble"><strong>{pick.selectedTeam}</strong><small>{pick.confidencePoints??'—'} pts</small></span>:<span className="blank-bubble">—</span>}</td>;})}<td className="record"><span className="total-bubble">{row.total}</span></td></tr>)}</tbody></table></div></section>;
}
